#!/bin/bash  
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
apt update
apt install jenkins
systemctl start jenkins
ufw allow 8080
ufw allow OpenSSH
ufw enable
sudo cat /var/lib/jenkins/secrets/initialAdminPassword >> /home/ubuntu/Jenkins/UnlockPassword

exit 0
